name: Performance

on:
  workflow_dispatch:
    inputs:
      cloud_vision_fallback:
        description: 'Activate cloud vision fallback'
        required: true
        default: 'false'

jobs:
  perf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Cache dependencies
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/test-requirements.txt') }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r test-requirements.txt
      - name: Login to GCP
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
      - name: Copy charges
        run: gsutil -m cp -r gs://${{ secrets.SERVICE_BUCKET_NAME }}/charges_schroeder ./data
      - name: Copy models
        run: gsutil -m cp -r gs://${{ secrets.SERVICE_BUCKET_NAME }}/checkpoints ./data
      - name: Test performance of car attributes detection
        run: pytest ./tests/test_performance.py -s --no-cov
        env:
          CLOUD_VISION_FALLBACK: ${{ github.event.inputs.cloud_vision_fallback }}
          PERFORMANCE_TEST: true
